import hoc from "../utils/hoc";
import Counter from "./components/Counter";
import Input from "./components/Input";
import TextArea from "./components/TextArea";
import Select from "./components/Select";
import Table from "./components/Table";
import Column from "./components/Column";
import Button from "./components/Button";
import Modal from "./components/Modal";
export { Counter, Input, TextArea, Select, Table, Column, Button, Modal };
